### ISSUE TITLE
Getting "Failed to Create Reminder" today

### ISSUE THREAD

**Issue by p1neapples** [laconalabs/LaconaApp#100]
![screen shot 2016-06-28 at 2 07 43 pm](https://cloud.githubusercontent.com/assets/7061032/16427972/dc221a48-3d3d-11e6-906d-6b38f3df898d.jpg)

On Mac El Capitan 10.11.4 with Lacona beta 11, I'm thinking it may be iCloud related, but I'm successfully logged into iCloud on my mac with reminders connected as well. Any thoughts anyone?

**Comment by brandonhorst** [comment]
There are two reasons why this could happen.
1. You did not give Lacona permission to access reminders. This can be changed in System Preferences -> Security & Privacy -> Privacy -> Reminders
2. You do not have a "default reminder list". The most common reason _this_ happens is because you don't have any reminder lists at all (in which case you should create one). If you do have a reminder list, then you can set the default from the menubar: Reminders -> Default List.

All of that also holds true for Calendars/Events.

**Comment by brandonhorst** [comment]
Fixed: https://twitter.com/p1neapples/status/750376500243886080
