### ISSUE TITLE
changing keyboard shortcut doesn't seem to reliably work

### ISSUE THREAD

**Issue by paultopia** [laconalabs/LaconaApp#102]
The UI for changing the keyboard shortcut seems a bit finicky.  A few days ago, after repeated tries, I managed to get it to agree that shift-spc was to be the shortcut.  Now, rethinking that, I can't get it to change to anything else at all.

Part of the issue might be that it isn't terribly clear how to interact with the input field for keyboard shortcuts.  Do you click on it once, and then enter keystrokes?  Double-click on it then enter keystrokes?  Right-click on it? (Evidently not, since that just reloads.) Click on it then hit enter then hit keystrokes?  Click then escape then keystrokes?  I've tried all those things, and it just doesn't change...

**Comment by oskarkrawczyk** [comment]
It works as any other shortcut assigner on macOS, if it's in focus you just assign a shortcut. That said perhaps the issue with reasigning you're having has an underlying problem I've mentioned in #101

**Comment by brandonhorst** [comment]
A single click should make a blue outline appear around the box. After that, you can press any combination of keys and it should change the display to show them, with a few exceptions:
- It will not take any key that is already in use by a global shortcut from another application or the system.
- There must be at least one modifier key (shift cmd alt ctrl) **and** one non-modifier key. So `a` will not work (no modifier), and `CMD+CTRL` (no non-modifier) will not work, and `CMD+a` will not work (global shortcut) but `CTRL+A` **should** work.
- The only exception is that the F keys (F1-F12) can be used without a modifier key, since on most Mac keyboards you do need to press the Fn key to even press them.

If you are seeing behavior other than what I have just described, please let me know.

I will add a small bit of description text to explain how to use the input.

**Comment by markfriedman** [comment]
Now I can’t find that box!  No matter.
Are you considering a desktop app independent from your web app?

Thanks 

Mark R Friedman, Photographer
2 Decker Rd, Ossining, NY 10562
https://mark-friedman.com http://mark-friedman.com/
mark@mark-friedman.com mailto:mark@mark-friedman.com
(914) 762-7689 - home
(914) 703-0402 - cell

**Comment by brandonhorst** [comment]
I'm not sure I follow. What web app are you referring to?

**Comment by markfriedman** [comment]
I’m not referring to a web app tied to a browser— I’m thinking how useful this would be across my devices as a standalone app:  Two, actually — one for Mac OS and one for IOS.
In your copious spare time, of course.

Mark R Friedman, Photographer
2 Decker Rd, Ossining, NY 10562
https://mark-friedman.com http://mark-friedman.com/
mark@mark-friedman.com mailto:mark@mark-friedman.com
(914) 762-7689 - home
(914) 703-0402 - cell

**Comment by brandonhorst** [comment]
A mobile app would be an interesting design challenge, because typing kinda sucks on mobile. It's definitely not in the works for right now, but maybe in the distant future.

You said 

> Now I can’t find that box!

What did you mean by that?

**Comment by brandonhorst** [comment]
Closing due to unclear problem description. Reopen if you're still having issues.
