### ISSUE TITLE
{bug} turn off display and lock computer

### ISSUE THREAD

**Issue by trungc3** [laconalabs/LaconaApp#107]
Can't not use this feature: "turn off display and lock computer"
Version: 0.10

**Comment by brandonhorst** [comment]
OK, so `lock computer` broke with 0.10.0. I see the problem and it'll be fixed in the next version.

`turn off display` works just fine.

I don't believe that `turn off display and lock computer` ever worked. Are you suggesting that you should be able to run multiple simple commands with one sentence? Or am I misunderstanding?

**Comment by trungc3** [comment]
I saw this feature _You can now toggle multiple settings with the same command ("turn off wifi and bluetooth")_ in new release and I think can run multiple simple commands ^^

**Comment by brandonhorst** [comment]
I see the confusion there. In particular, the settings that can be used in combination are `do not disturb`, `mute`, `wifi`, `bluetooth`, and `dark mode`.

I'll look into what it would mean to have more commands be combinable, especially the basic system commands like `log off`, `start screensaver`, `lock` that sort of thing

**Comment by brandonhorst** [comment]
Lock was fixed in Beta 13 ([0.10.1](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md)). I'm going to hold off on 'multiple verbs combined with and' for the time being. Thanks for reporting.
