### ISSUE TITLE
Use heavier font weight or give options to change weight/size

### ISSUE THREAD

**Issue by sebj** [laconalabs/LaconaApp#108]
Currently, results are somewhat difficult to read due to the light/thin font weight.

A heavier font weight to match Spotlight would be immediately better, but in the long-term customisation options similar to Alfred for size/weight, colours etc. might be useful.

**Comment by brandonhorst** [comment]
What are other user's thoughts on this?

Some background. When I added off-to-the-right output results, I knew that I needed to shrink the bar horizontally a bit for folks on small screens (esp. 11-in Macbook Airs). I decided that the old font size (still visibile on [lacona.io](https://lacona.io)) resulted in too much wrapping. This also worked with the introduction of icons - if the icons were too big, they'd take up way too much of the window.

Another interesting thing - the results are actually _larger_ than the Spotlight results (at least with default settings). However, colors and dark backgrounds do tend to make text look lighter, so that plays in.

That said, I'm treating it more as a trial run - if you think that there are design elements that could be tweaked, let me know. We have one vote for bringing back the large text

**Comment by sebj** [comment]
I see.

I have no issue with font-size, just weight. It looks like the light weight of the font is being used vs Spotlight which uses the regular weight of the system font, unless it's a glitch on my screen.

Alternatively, a darker colour for text might improve visibility.

But would Alfred-style customisation options be possible in future?

**Comment by brandonhorst** [comment]
A darker color text would definitely help, especially on the minimal themes.

Customization is possible in the future but not a priority. Because of some of the Lacona interface quirks (the small argument descriptors, the popover), the interface tuning is fairly precise. I could definitely see customizing colors, but font sizes are trickier. That is a feature that I see coming with Lacona 2.0.

**Comment by brandonhorst** [comment]
The "Large Fonts" option was released with 1.0.0.
