### ISSUE TITLE
Lacona Settings and/or Preferences not opening

### ISSUE THREAD

**Issue by syeluru** [laconalabs/LaconaApp#117]
Might be a Sierra beta issue, but when I try to open either the Lacona preferences or Lacona settings  from the Lacona app, nothing shows up no matter how long I wait. Neither of the things in the below video work for some reason. Not preventing use of the app, but would love to see what the preferences/settings are. Thanks!

<img width="558" alt="lacona-settings-pref" src="https://cloud.githubusercontent.com/assets/12750109/17080399/3b50936e-50f3-11e6-8f64-a1795fd4fc95.png">

**Comment by brandonhorst** [comment]
No, it's my fault. That command was broken with Beta 12.

It'll be fixed in the next version. Until then, you can still access the preferences from the Menu Bar icon, or by pressing CMD+, while Lacona is active.

![image](https://cloud.githubusercontent.com/assets/1938545/17080897/91894f16-510f-11e6-9566-d608cdf1cedc.png)

**Comment by syeluru** [comment]
Awesome, thanks!
