### ISSUE TITLE
Clipboard history

### ISSUE THREAD

**Issue by Misophistful** [laconalabs/LaconaApp#132]
The feature I miss most from Alfred is "clipboard history", which I use multiple times per day. Is there any chance of that feature being added to Lacona?

**Comment by brandonhorst** [comment]
This is the sort of feature that I think is best handled by a separate app. [A number of them exist](http://superuser.com/questions/17200/how-do-i-view-my-clipboard-history-on-os-x). I would prefer to see a Lacona addon that interfaces with an existing app (perhaps via Applescript?), rather than adding this functionality to Lacona core. Do one thing well, y'know?

Alfred itself does not expose an API, and many of the big tools don't either - but I'll be looking for a good option, because this would be a good thing to support.

**Comment by Misophistful** [comment]
I understand how you're thinking, and agree that doing one thing well is critical for having a compelling and successful product. If you can maintain that mindset, then I predict big things for Lacona!

I guess the reason both Alfred and Launcher decided to implement it directly in their apps (rather than connect with an existing clipboard manager), is to give all of their users a consistent experience around a common "power user" feature. But the more I think about it, the more it feels like diluting their core experience, and becoming a "jack of all trades".

Thanks to your link I found Paste (http://pasteapp.me), so I'm going to buy that and see how I get on running it alongside Lacona.
