### ISSUE TITLE
Add Light theme

### ISSUE THREAD

**Issue by brandonhorst** [laconalabs/LaconaApp#17]
There should also be a setting (the default) to select light/dark theme based upon the Light Mode/Dark Mode OS setting.

**Comment by agustif** [comment]
http://cl.ly/1o3Z252C3N3S/Image%202016-01-30%20at%2011.42.33%20PM.png
The Clock from the App Store does this pretty well I think.
If you select the 'Same color as system checkbox you can't edit your choice on the theme settings which is overrided by the system settings.

uBar - http://cl.ly/2x0G0z150H3x
uBar takes less space for the matter putting all the options in a only option text dropdown selector, which to me is not that ui friendly but it does take less space.

PS.
I'd use the light theme because sometimes I just run 3 scripts to Invert Colors + Grayscale + Increase Contrast in order to have my Mac "Dark Mode" System and app wide, every app comes in white, which some inusual like fantastical having a mixed UI. So I'll subscribe to this issue!

**Comment by brandonhorst** [comment]
@agustifernandez Thanks for the feedback! For now, I am going to keep the settings in the menubar dropdown, until a proper settings page is built. But when that happens, I'll look back at this for sure.

**Comment by brandonhorst** [comment]
Added with https://github.com/lacona/LaconaApp/releases/tag/0.3.1 - "Check for Updates..." to download it now!
