### ISSUE TITLE
Apps outside of the default "Applications" folder are not shown

### ISSUE THREAD

**Issue by luispedrofonseca** [laconalabs/LaconaApp#21]
I have two partitions and on my second partition I keep a folder with all the apps that are portable and don't need to be reinstalled on a system format.
These applications don't show up on Lacona.

**Comment by brandonhorst** [comment]
Yeah, this is a limitation. The problem is that there are actually a TON of apps on your system (go to your terminal and run `mdfind kind:application`, and we don't want a bunch of false positives every time you try to open an app. There will need to be a way to select which directories to search (like how it works in Alfred).

**Comment by brandonhorst** [comment]
As of [0.4.1](https://github.com/lacona/LaconaApp/blob/master/CHANGELOG.md), Lacona will now show apps in:
- `/Applications` - System, App Store, and normal Apps
- `/Applications/Xcode.app/Contents/Applications` - Developer utilities, if Xcode is installed
- `/System/Library/CoreServices/Applications` - System utilities
- `~/Applications` - Chrome Apps, among other things
- `/usr/local/Cellar` - Apps installed via Homebrew
- `/opt/homebrew-cask/Caskroom` - Apps installed via Homebrew Cask
- `Finder.app`

However, this probably still doesn't handle your case. We need an interface to manage the search directories, which will come with https://github.com/lacona/LaconaApp/issues/26

**Comment by brandonhorst** [comment]
This is now user-configurable as of [0.5.0](https://github.com/lacona/LaconaApp/blob/master/CHANGELOG.md). Thanks for submitting this!
