### ISSUE TITLE
Allow the use of any keyboard shortcut to trigger Lacona.

### ISSUE THREAD

**Issue by kleinmaetschke** [laconalabs/LaconaApp#33]
Limiting to a modifier + space is pretty restricting. It'd be helpful to use any given trigger. I, for instance, use F19 with Alfred.

**Comment by brandonhorst** [comment]
You can use `1-4 modifiers` + `any key` (not just space). Right now it doesn't allow a single key without a modifier (so that you can't accidentally set the key to `F` and then have Lacona mess up your typing and get frustrated. 

I suppose that in the case of the `F#` keys that makes sense. I could modify it so that F\* keys can be used without a modifier.

**Comment by brandonhorst** [comment]
As of [Public Beta 3](https://github.com/lacona/LaconaApp/blob/54425cbe4f04bc1ec089ff2b825ffbd047085eea/CHANGELOG.md), you can use un-modified F-keys as a keyboard shortcut. F19 should work just fine. Thanks!
