### ISSUE TITLE
Feature request: github integration

### ISSUE THREAD

**Issue by nunoh** [laconalabs/LaconaApp#50]
Very much like [gharlan/alfred-github-workflow](https://github.com/gharlan/alfred-github-workflow). That would be aaaawesome! :bow:

**Comment by brandonhorst** [comment]
It would be cool! This is an example of something that would be great to write after the developer API comes out (in March!), maybe by me, maybe by someone else. I'll keep it on the radar!

**Comment by Nxt3** [comment]
Oh shoot I forgot about the dev API! Looking forward to that man!

**Comment by brandonhorst** [comment]
Lacona Custom Addons are now available (for development only). Give it a shot! [docs.lacona.io](http://docs.lacona.io/)

**Comment by brandonhorst** [comment]
More info: A Github plugin doesn't currently exist, but it wouldn't behard to build.

The simplest thing would be to create a new Phrase (`GithubRepo`) that extends `lacona-phrases#URL`. That would make it automatically work with the `open` phrase, like `open laconalabs/elliptical`. Extensions are documented [here](https://docs.lacona.io/docs/extensions.html).

If you wanted it to support Autocomplete, like the Alfred workflow does, you would also need to create a Dynamic Source (`<dynamic />`). Docs are a bit spotty at the moment, but you would want to follow the example of [`lacona-osx#SpotlightFile`](https://github.com/laconalabs/lacona-osx/blob/master/src/spotlight-fs.jsx), except you would want to call [`lacona-api#callNode`](https://docs.lacona.io/docs/api.html#callnode) rather than `querySpotlight`.

Then, you could take it a step up: you could add new github-specific commands:
- `clone laconalabs/elliptical to <Folder>`
- `fork laconalabs/elliptical`
- `star laconalabs/elliptical`

Once you have a `GithubRepo` phrase, the sky's the limit.

I'd be happy to help you build, because I know docs are spotty - I'd be happy to chat on the public [Gitter](https://gitter.im/laconalabs/LaconaApp).

**Comment by brandonhorst** [comment]
A simple version of this is now available as the Github Addon. Update to Lacona 1.1.0 and try it out!

If you have feature requests within the Addon, pleas submit them [on the Addon repo](https://github.com/brandonhorst/lacona-github).

I hope it's useful to you!
