### ISSUE TITLE
Feature Request: implement basic Spotlight commands

### ISSUE THREAD

**Issue by Your3xcelency** [laconalabs/LaconaApp#52]
Looking at some previous comments, I realize this may seem like a bit much, and I don't mean to sound rude. This is simply me dumping my ideas. If these don't sound like good ideas, that's fine. I'm SUPER excited about Lacona, and hope at least one of my ideas can find a place in the official versions.

Here are a couple of the features that currently prevent me from using lacona instead of spotlight - things I feel should be in the final version but are not currently (No rush, just hopefully before full release?)
Basic arithmetic - things like 327/4.3 should be implementable, as mentioned in #16.
Basic conversions - 10 inches in centimeters.
Then we get to more complicated things - weather, search by age (documents i worked on last week).
Searching by first letters of files would be great, things like typing "ftb" for "Feed the Beast", etc.
Sports scores.

If possible, maybe use the spotlight index? Kind of like Alfred does.

Don't mean to overwhelm you here, but if you have a bit of time and are thinking of some features to add, maybe this would help?

http://www.macworld.com/article/2973548/operating-systems/hands-on-with-spotlight-in-el-capitan-location-info-natural-language-searches-ui-tweaks-and-more.html

ALSO, IF YOU COULD DO THIS YOU WOULD BE MY MASTER:
Allow texting completely from within lacona, eg. ("Text Tony Stark how are you today?").
Possible methods of implementation - rather than an ugly dialog box for confirmation (what a lot of other app use), try using a share sheet (the overlay that pops up when you use the share option in safari to email a webpage to someone?). If the information is already filled in, it would look gorgeous, AND be fully functional.

Let me know what you think:
thearyaskumar@icloud.com

BTW, this is what a share sheet looks like:
<img width="887" alt="screen shot 2016-02-14 at 12 45 32 pm" src="https://cloud.githubusercontent.com/assets/17236678/13035250/e1133e90-d318-11e5-9208-ebbfd9f473e2.png">

**Comment by Nxt3** [comment]
I don't mean to be rude--but you sure are demanding a lot and not being too nice about it. I think it's very rude of you to tell him how to run his app--telling him he should do certain things for a few weeks before progressing. I certainly don't see you making a Spotlight competitor. 

Claiming that it should "be easy" to implement something isn't really up to you--it's up to Brandon. You don't know how he's coded it up. Besides, he already has plans to implement computations (#16).

Lastly, this is a beta. The app isn't done or near completion; he's adding in stuff every day. These things take time. He's already stated the goal of Lacona is to replace Spotlight; I believe what he says--but obviously it won't happen overnight.

**Comment by Your3xcelency** [comment]
Apologies - I didn't mean to be rude, however when I developed apps I found it incredibly useful to get community feedback. I was just dumping my thoughts out. Didn't mean to appear rude, rather, I see so much potential in Lacona, and don't want it to go to waste. I understand this is asking a lot, but by no means do I expect it all to bear fruit. Simply, I hope that one or two of these ideas may find themselves in a future generation of lacuna. Apologies once again if this came out in the wrong way - This was not my intention.

**Comment by Your3xcelency** [comment]
Updated original questions to reflect your suggested rewording - sorry if it appeared rude the first time around.

**Comment by brandonhorst** [comment]
Haha, it's good to see people passionate about useful features!

Could you do me a favor and break up this issue into a few smaller issues, each suggesting one thing? That would allow a more fruitful discussion of each.

---

Now, to answer the spirit of your suggestions: those things would all be awesome. As I've stated elsewhere, the eventual goal is to replace Spotlight - the intermediate goal is to focus on the features that Spotlight cannot do. For the time being, it will be a pain to use 2 different systems, but hopefully it won't be for much longer!

As you know, the goal is to open the developer API so anyone can build fancy new commands. That is going to be my priority until it happens. After that, we will focus on adding shiny new features! Of course, there is nothing wrong with suggesting new features - just know that they are taking a back-seat to extensibility at this point.

To give you a rundown, here's what needs to happen, roughly in order:
1. Lacona needs a Preferences system. This includes not only Lacona prefs and built-in command prefs, but it needs to be designed in a way that custom commands can have (at least basic) prefs as well. This is about 75% complete and should be launching this week or early next week. It uses [confine](https://github.com/brandonhorst/confine) and [react-confine](https://github.com/brandonhorst/react-confine), if you're curious.
2. Lacona needs a Results Preview system, as discussed in https://github.com/lacona/LaconaApp/issues/31. This is still in the design phase. Right now I'm leaning toward the "mimic Spotlight" suggestion, but I want to mock up a few different options before showing them off. If you have input, please share it on that issue!
3. I need to finalize the [`lacona`](https://github.com/lacona/lacona) API. At a certain point, I will declare it 1.0.0, and future releases will follow [Semver](http://semver.org/). Major versions changes will be few and far between (because they could result in broken commands), so I need to make sure that it's _good enough_ to do what it needs to do before releasing it. The same holds true for the built-in phrases (lacona/lacona-phrase-*)
4. Lacona needs an interface to discover and install new custom commands. It will _probably_ use `npm` under the covers, but that may change.
5. There needs to be at least a few docs to help devs start building new commands.

Then, I will open the API to developers and folks can build fancy commands like the ones you are suggesting! It is _possible_ that number (2) will actually will come after the API release - I haven't decided that one yet.

I hope that this will all happen by the end of March. Then you will be able to build all of these cool commands yourself. Get pumped!

**Comment by brandonhorst** [comment]
Thanks for branching these off. I'll close this issue.
