### ISSUE TITLE
Using Spotlight Index

### ISSUE THREAD

**Issue by Your3xcelency** [laconalabs/LaconaApp#57]
Hey,

I am not familiar with the spotlight index, and don't know if this is possible to implement. However, Spotlight does incorporate (rudimentary) Natural Language Parsing, Searching by file name/type, Searching "ftb" for "Feed The Beast", and (basic) machine learning. 

Would using the spotlight index be a possibility?

Thanks,
Your_3xcelency

**Comment by brandonhorst** [comment]
So Lacona actually does use Spotlight for most things. Its lists of applications, bookmarks, files, and preference panes all come directly from the Spotlight API (`NSMetadataQuery`).

However, in choosing which functionality to use and which to skip, I want to be smart. Lacona is first and foremost a command runner, and only secondarily a search tool. One important thing to maintain is the connection between your input and the suggested outputs.

Take this spotlight query for example. I just searched your example `ftb` to see what it would come up with. It recommended a random Mathematica file called `MM10F09.nb`.

![image](https://cloud.githubusercontent.com/assets/1938545/13132832/58d9db70-d5c4-11e5-9b94-3827d7253222.png)

This is fine for a search tool because the relationship is very clear - `MM10F09.nb` must contain `ftb` somewhere. But for a command tool, it's a bit weirder. If I typed `open ftb` and the autocomplete suggested `open MM10F09.nb` - I would be confused and weirded out. But completing it `FeedTheBeast.txt` (whatever that is) seems more natural. Basically, for every output, you should understand exactly why it's there.

So to review your examples, I would want the "open" command to support `ftb => feed the beast` (I would call this "fuzzy matching", like Sublime Text), but I would not want it to support type or contents matching. I'm not entirely sure what you mean by machine learning.

I think that the best way to handle this is to bury this functionality behind a "find" or "search" command, but do NOT expose it for "open" (and its eventual kin). This will require some low level changes, because now [lacona/lacona](https://github.com/lacona/lacona) straight up refuses to show any output that does not contain the input in some way, but I think that it would be a useful addition to supplant Spotlight.

**Comment by Your3xcelency** [comment]
Cool! Didn't realize you were running Spotlight behind the scenes. By Machine Learning, I meant that it "Learns" which apps you use, and shows those results more often. However, you may already be doing this if you use NSMetaDataQuery (I'm not too familiar with it). And, on a completely unrelated topic, here's a tip for when you make the dev docs. You know that typing (Command + Shift + 4) lets you select an area of the screen. However, try typing space once you see the crosshairs. It will let you select a window, rather than just an area on the screen. 

Thanks,
Your_3xcelency

**Comment by brandonhorst** [comment]
Slick! Never heard of that whole press-space-during-screenshot thing. I only knew about `screencapture -W` and was always too lazy to use it.

Discussion about "Learning" is here: https://github.com/lacona/LaconaApp/issues/48. I'm still not entirely sure how I want to manage it, so feel free to contribute to the discussion over there.

**Comment by brandonhorst** [comment]
Searching by filename will be tracked in https://github.com/lacona/LaconaApp/issues/61

Searching by fuzzy matching will be tracked here https://github.com/lacona/LaconaApp/issues/62

I'll close this issue out, and we'll keep the discussion going in those issues. Thanks!
