### ISSUE TITLE
List all options when pressing enter on a generic command

### ISSUE THREAD

**Issue by revolter** [laconalabs/LaconaApp#60]
I don't know how to best title this issue. I'll explain it using an example.

When I type `eject`, I get this options:
- `eject all`
- `eject` <kbd>volume</kbd>

It would be nice (I don't know if possible, at least in this case), if, when I press <kbd>enter</kbd> on the second option, the list changes to:
- `eject ClipMenu`
- `eject Lacona`

and so forth.

**Comment by brandonhorst** [comment]
This is a bit tricky, because you want this behavior for certain commands (Eject is one of them), but you don't necessarily want it for others (typing "play " doesn't necessarily mean you want to see a list of every song that you have).

Of course, once Lacona "learns" (https://github.com/lacona/LaconaApp/issues/48) your top choices, perhaps you _would_ want to see every song that you have, sorted in the order of those you play most often.

This is a really easy thing to do in the underlying [lacona](https://github.com/lacona/lacona) parser (`supressEmpty={false}`), we just need to make intelligent decisions about WHERE to use it to provide the best user experience.

**Comment by revolter** [comment]
And how would these decisions be made? Can this have a generic solution or just a custom mapping that describes that, for example, for the `eject` command, the entire list should show up? Or just like, if the resulting list has under ~20 elements, it should show up?

**Comment by revolter** [comment]
@brandonhorst I think this is fixed by the latest update, right?

**Comment by brandonhorst** [comment]
Ah yes, I missed this one. I added `suppressEmpty={false}` to many more built-in phrases. If you have suggestions of more to add, let me know!
