### ISSUE TITLE
[Suggestion] Save sentence use for later

### ISSUE THREAD

**Issue by ekarious** [laconalabs/LaconaApp#72]
If i write `open twitter.com in Safari`, when i start to write it again, it would be nice to have in suggested to me again.

What are your thought about this ?

**Comment by ShilohBeeler** [comment]
This is essentially #48, which is having Lacona learn what you use the most and adapting to this. You can read that thread for some of the complications that arise from this. I believe this is a feature which is already being worked on.

**Comment by brandonhorst** [comment]
Yeah, I think that the root desire is "making very common commands quicker".

I see two good ways to do that. One is intelligent sorting, which as @Shymain said is on #48. It's in-progress right now. It's a difficult and complex issue, but definitely worth doing.

However, `open twitter.com in Safari` would never be handled adequately by sorting, because `twitter.com` is a freeform input, not a sortable suggestion.

For that, I see two good solutions:
1. _Aliases_ - user-configurable, no-code-required string mappings - perhaps something like "twt" -> "open twitter.com in Safari". So you can type "twt" and it will automatically expand it. This gets tricky if you want to support aliases that accept variables, but it CAN be done right and it would be very useful.
2. _Keyboard Shortcuts_ - I have always seen this as the pinnacle of productivity - being able to map a globally-available or context-dependent Keyboard Shortcut to a natural language string, so that you can use it whenever. Mapping `CMD+CTRL+t` to "open twitter.com in Safari" would be wonderful.

I think that these both support the end-goal of increasing power-user productivity for common phrases, without polluting the interface with too much "magic" suggestion.

How do you feel about these, @Kitefr? Would this fulfill your use case?

**Comment by brandonhorst** [comment]
Aliases will be released in 1.0.0. I think that this should these needs for now.

**Comment by brandonhorst** [comment]
With 1.0.0, we now have aliases. So you could add a "twsaf" alias for "open twitter.com in Safari" and it should accomplish the same purpose. Thanks for reporting!
