### ISSUE TITLE
No way to access settings without manubar icon

### ISSUE THREAD

**Issue by ghost** [laconalabs/LaconaApp#79]
I have set Lacona to not have a menubar item, since there are way to many, now there is no clear way to access preferences.
It works if you hit the shortcut for Lacona and then the keyboard shortcut for Preferences, but that is not very clear, especially for people not used to work with keyboard shorcuts.
A better way to do it (maybe) would be that some kind of menu opens when you launch the app again, while it is running, like bettertouchtool for example.

**Comment by brandonhorst** [comment]
This is certainly a problem that should be solved. I don't think BTT's solution works great for this app, because I would like pressing the Dock Icon (or opening the app again) to show the Lacona bar itself (like how Alfred works). Lacona doesn't actually do that right now, but I would like it to.

I think that a good solution for this is to present "open Lacona Preferences"/"open Lacona Settings" as a command. I see this as a very Lacona-way to solve this problem. I admit that it's not quite as discoverable as the dock icon, but I think that it is a bit more in line with user expectations (at least those coming from Alfred).

Does anybody know how Flashlight did it? I don't actually remember.

**Comment by ghost** [comment]
Hm, i agree, that was actually the first thing i tried ;)

**Comment by ghost** [comment]
I find that opening the lacona bar (CMD + Space) and then hit (CMD + ,) is easiest. Menu bar doesn't have to be enabled.

**Comment by brandonhorst** [comment]
@hagabla noted that in the first post. I agree with you - but that is not particularly discoverable for folks that aren't familiar with common shortcuts. I think we should support both.

**Comment by brandonhorst** [comment]
This functionality was added in [Beta 8](https://github.com/laconalabs/LaconaApp/blob/master/CHANGELOG.md). Try it out!
